[package]
name = "gitmoji-selector"
version = "0.1.0"
authors = ["Tom Houlé <tom@tomhoule.com>"]
edition = "2018"

[dependencies]
serde_json = "1.0.38"
serde = "1.0.87"
serde_derive = "1.0.87"
regex = "1.1.0"
failure = "0.1.5"
